[variables]
DISCORD_TOKEN = ""
DISCORD_CHANNEL_HR = ""
DISCORD_CHANNEL_NBA = ""
DISCORD_CHANNEL_WNBA = ""
BALLDONTLIE_API_KEY = ""
POST_HOUR_ET = ""
POST_MINUTE_ET = ""
NBA_POST_HOUR_ET = ""
NBA_POST_MINUTE_ET = ""
